language: node_js
node_js: lts/*
os: osx
osx_image: xcode10.2
before_install:
  - brew update
install:
  - yarn install
script:
  - yarn test
before_deploy:
  - yarn install
  - yarn build
deploy:
  provider: npm
  email: shamofu@gmail.com
  api_key:
    secure: c/6UEx2nQZ9qFM0kM4Cx/Fmber+WgUfnTFAAgVELXj4GajR/s2kBxgWdM4uVol2r0GxoJF+tZn9aeq71vK5WLcglD49z9h+XrjJNEmVs8/tOKceqqWw3TBNxPzLSEkIXjvPDkb+5CZZQQZsNktopCGKYWIou9jp6ElNOWGu9gNpdVUvLBmc18TgTA3DE+w1PK/F8KqNiszYS7ktBcFAc/22xGiB5jhnhCfmjAB7i6RYjZeuCNFSG4XGbA2A9jNCDXdpaY+nfERMBzY5w692I7JIx9g+MiZPwZeoY0pBfh2O9XcgVtI4W1TovNpftYlnRX6WmC7Xpw+8t1cPx1SmazKazfCxFRKKdRAUfOLByyr4WniX/sD0Oyk2D941qPKyUcos9t+/sanvXMeONBTz9hh62vhzbcF3i0HXj9DulgrjJeVaR21GZB2LLwQ86xDZwz2QGIQa7ILrwex1PHJ8z85Dg9Rq19icDYf0UTZEgLKDMVe2LDoAPSLvMlsqJ25oJmJAON9qCuXzpMXSFtDyYY6hbL/BbnCz2/qbMK/uAfiiObXwC0CLfi4OY5M1NAYZEl+OIMwgj4IWK9C4gZnHZze3nKPEGcpvBqTSYfCwI1jD3TU9uT7JVms1Uo44C4mAPUB6yX/N8JjYX1/dP28heJsEpu39rC3DCYbeECh4XVEI=
  skip_cleanup: true
  on:
    tags: true
    repo: shamofu/npm-check-licenses
    branch: master
